# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: admission-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: yunikorn
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: admmission-cleanup
      labels:
        app: yunikorn
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount }}
      containers:
        - name: curl
          image: "{{ .Values.global.curlImage.repository }}:{{ .Values.global.curlImage.tag }}"
          imagePullPolicy: {{ .Values.global.curlImage.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - >
              APISERVER=https://kubernetes.default.svc;
              SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount;
              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace);
              TOKEN=$(cat ${SERVICEACCOUNT}/token);
              CACERT=${SERVICEACCOUNT}/ca.crt;
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/apis/apps/v1/namespaces/${NAMESPACE}/deployments/yunikorn-admission-controller;
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/apis/apps/v1/namespaces/${NAMESPACE}/services/yunikorn-admission-controller-service;
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/yunikorn-admission-controller-mutations;
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/yunikorn-admission-controller-validations;
      restartPolicy: Never
